#!/bin/bash
#PBS -N two_tabulate
#PBS -m abe
#PBS -M zhangshuo01@sjtu.edu.cn
#PBS -l nodes=1:ppn=72
#PBS -l mem=300gb
#PBS -l walltime=40:00:00
#PBS -q normal
#PBS -j oe
#PBS -o /home/shuoz/sl_inference_3Dinfer_hdf5_server/two_tabulate1.log

source ~/miniconda3/etc/profile.d/conda.sh
conda activate base

cd $PBS_O_WORKDIR
echo "Start PBS job"

cd /home/shuoz

echo "Generating mock + tabulate for index 2"
python3 -m sl_inference_3Dinfer_hdf5_server.tests_eta.run_all --index 2 --force-new-mock


echo "All done."

